### ISSUE TITLE
link to this paper

### ISSUE THREAD

**Issue by Sandy4321** [czopluoglu/Duolingo_paper#1]
may you share link to this paper please 
Comparative Study of Item Response Theory Models for Mixed Discrete-Continuous Responses

**Comment by czopluoglu** [comment]
It is under review right now. I will post the link once it is published.

**Comment by Sandy4321** [comment]
great thanks
hopefully it will be soon 
but code was published 2 years ago?
do  you have some where published parts of this material ?
